on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'development'
      branch:
        description: 'Branch'
        required: true
        default: 'uat'
  repository_dispatch:
    types: [dev]
       
           
name: deployEKS

permissions:
  id-token: write
  contents: write

env:

  CONTEXT_PATH: '.'
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    environment: dev
    name: Deploy new image to ECR
    runs-on: ubuntu-latest

    steps:

       
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: GitHubActionSession

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        run: |
          IMAGE_TAG="latest"
          IMAGE_URI="${{ secrets.ECR_REGISTRY }}/${{ secrets.REPOSITORY }}:$IMAGE_TAG"
          echo "Building image $IMAGE_URI..."
          docker build -t "$IMAGE_URI" -f Dockerfile .
          echo "Pushing image to ECR..."
          docker push "$IMAGE_URI"
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.REPOSITORY }}
          AWS_DEFAULT_REGION: ${{ secrets.REGION }}

